name: Generar feed Siglo 21

on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  generar-y-publicar:
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Preparar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Instalar dependencias
        run: pip install requests

      - name: Generar feed
        run: run: python generar_feed_nuevo.py

      - name: Preparar publicación
        run: |
          mkdir public
          cp feed.xml public/feed.xml

      - name: Configurar GitHub Pages
        uses: actions/configure-pages@v5

      - name: Subir archivos de Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

      - name: Publicar en GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
